services:
  api:
    build:
      context: .
      target: production
    container_name: chrono_backend
    ports:
      - 4000:4000
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - chrono

networks:
  chrono:
    external: true