services:
  api:
    build:
      context: .
      target: production
    container_name: chrono_backend
    network_mode: bridge
    ports:
      - 4000:4000
    env_file:
      - .env
    restart: unless-stopped
